### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by blackjyn** [nkronlage/JavaScripture#21]
cloned the repo to D:\Repo and got error 
**process_begin: CreateProcess(NULL, ls -d content/*, ...) failed.
File not found - *.jsdoc
File not found - *.jsdoc
File not found - *.jsdoc
File not found - *.jsdoc
node makeapisets.js
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'D:\Repo\JavaScripture\tmp\new_apisets.
json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at Object.<anonymous> (D:\Repo\JavaScripture\makeapisets.js:24:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16) 
make: *** [tmp/apisets.json] Error 1**

**Comment by nkronlage** [comment]
blackjyn, I have switched the build system to use gulp which should work equally well on Windows or Unix based systems.  Please try it out and see if it works for you.  

Note, it will currently rebuild all files each time you run gulp since I haven't been able to get caching to work yet.
