### ISSUE TITLE
Run Got Error

### ISSUE THREAD

**Issue by blackjyn** [nkronlage/JavaScripture#22]
I've installed all dependency successfully with no error msgs.
when i run "gulp" I got this error:

**D:\Repo\JavaScripture\jsdocparser.js:562
    member.optionalDepth = m.optionalDepth;
                         ^
TypeError: Cannot assign to read only property 'optionalDepth' of String
    at D:\Repo\JavaScripture\jsdocparser.js:562:26
    at Array.map (native)
    at parseParamList (D:\Repo\JavaScripture\jsdocparser.js:558:23)
    at parseMember (D:\Repo\JavaScripture\jsdocparser.js:387:27)
    at D:\Repo\JavaScripture\jsdocparser.js:561:18
    at Array.map (native)
    at parseParamList (D:\Repo\JavaScripture\jsdocparser.js:558:23)
    at parseMember (D:\Repo\JavaScripture\jsdocparser.js:387:27)
    at parseMember (D:\Repo\JavaScripture\jsdocparser.js:500:18)
    at D:\Repo\JavaScripture\jsdocparser.js:561:18
**

**Comment by nkronlage** [comment]
Thanks for trying out the new build system. Do you have any local changes to any of the files?  Also, what version of Node are you using?

**Comment by blackjyn** [comment]
I didn't change anything. running on Win 8.1 x64 with NodeJS v0.12.4
:(

**Comment by nkronlage** [comment]
I installed an updated version of Node and hit the same problem.  I uploaded a fix for this last night.  Thanks for finding these issues :)
